Repository coteditor/CotEditor, pull requests merged in 2024-09, with the labels that each got.

#1687 Fix korean localization
  CotEditor/mul.lproj/Main.xcstrings
Labels: localization

#1692 Add C++20 Keywords
  CotEditor/Syntaxes/C++.yml
Labels: enhancement

#1704 Fixed typo of Sponsos to Sponsors
  CotEditor/Localizables/DonationSettings.xcstrings
Labels: bug

#1707 Add new ko localization coteditor#1706
  CotEditor/Localizables/AppearanceSettings.xcstrings
  CotEditor/Localizables/Document.xcstrings
  CotEditor/Localizables/FormatSettings.xcstrings
  CotEditor/Localizables/GeneralSettings.xcstrings
  CotEditor/Localizables/Localizable.xcstrings
  CotEditor/Localizables/Sparkle.xcstrings
  CotEditor/Localizables/WhatsNew.xcstrings
  CotEditor/mul.lproj/Main.xcstrings
  CotEditor/mul.lproj/MultipleReplaceListView.xcstrings
  CotEditor/mul.lproj/SyntaxListView.xcstrings
  CotEditor/mul.lproj/ThemeListView.xcstrings
Labels: localization

#1715 Fix localization of `WhatsNew` Panel
  CotEditor/Localizables/WhatsNew.xcstrings
Labels: localization

#1723 Fix Polish (pl) localization
  CotEditor/Localizables/WindowSettings.xcstrings
Labels: localization
